#
# User configuration sourced by interactive shells
#

# Load antigen
source ~/.zsh/antigen.zsh

# Use oh-my-zsh as base
antigen use oh-my-zsh

# Plugins
antigen bundles <<EOBUNDLES
	osx
	git
	github
	docker
	docker-compose
	httpie

	zsh-users/zsh-syntax-highlighting
EOBUNDLES

# Configurations
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
export MANPATH="/usr/local/man:$MANPATH"

export LANG=en_US.UTF-8
export LC_ALL=$LANG
export EDITOR=nvim

# golang
export GOPATH=$HOME
export PATH=$GOPATH/bin:$PATH

# Local bin
export PATH=$HOME/.local/bin:$PATH

# Local dotfiles bin
export PATH=$HOME/.bin:$PATH

unsetopt share_history
unsetopt AUTO_CD

# rbenv
export PATH="$HOME/.nodenv/bin:$PATH"
eval "$(nodenv init -)"

# nodenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# yarn
export PATH="$HOME/.yarn/bin:$PATH"
export PATH="`yarn global bin`:$PATH"

# kiex
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

# hub
eval "$(hub alias -s)"

# iTerm2
test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# Travis
[ -f /Users/jonathanlima/.travis/travis.sh ] && source /Users/jonathanlima/.travis/travis.sh

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Aliases
source ~/.zsh/aliases.zsh

# Theme
source ~/.zsh/dracula.zsh-theme
 
